export const VACANCY_STATUS_ACTIVE = 1;
export const VACANCY_STATUS_EXPIRED = 2;

export const APPLICATION_STATUS_PENDING = 1 ;
export const APPLICATION_STATUS_SHORTLISTED = 2 ;
export const APPLICATION_STATUS_APPROVED = 3;
export const APPLICATION_STATUS_NOT_APPROVED = 4;
